### ISSUE TITLE
Database availability

### ISSUE THREAD

**Issue by manmolecular** [BiDAlab/HuMIdb#1]
Hello!

Is this database still available to download? I sent the e-mail request to atvs@uam.es, as was described in the README, but didn't receive any response.

**Comment by BiDAlab** [comment]
Dear,

the person in charge of the database is on holidays. Please contact again
September 1.

Best,
Aythami.


*Aythami Morales Moreno*
Associate Professor
Biometrics and Data Pattern Analytics Laboratory (BiDA-Lab)
Escuela Politécnica Superior / *School of Engineering*
Universidad Autónoma de Madrid - Campus de Cantoblanco
c/ Francisco Tomas y Valiente, 11 -
<https://maps.google.com/?q=c/+Francisco+Tomas+y+Valiente,+11+-%C2%A028049+Madrid+(SPAIN&entry=gmail&source=g>
28049
Madrid (SPAIN
<https://maps.google.com/?q=c/+Francisco+Tomas+y+Valiente,+11+-%C2%A028049+Madrid+(SPAIN&entry=gmail&source=g>
)
***@***.*** ***@***.***> - *https://aythami.me
<https://aythami.me>*

**Comment by manmolecular** [comment]
Thanks

**Comment by ranjithven** [comment]
My name is ranjith, phd student and is looking for the Humidb database. I sent the e-mail request to [atvs@uam.es](mailto:atvs@uam.es). can your please send the database as it would help me a lot
Regards
Ranjith

**Comment by BiDAlab** [comment]
Dear Ranjith,

thanks for your interest. Please send me the signed licence agreement. We will send you the download details once the agreement will be evaluated.

Best,
Aythami.
________________________________
De: ranjithven ***@***.***>
Enviado: domingo, 16 de abril de 2023 15:15
Para: BiDAlab/HuMIdb ***@***.***>
Cc: Aythami Morales Moreno ***@***.***>; Comment ***@***.***>
Asunto: Re: [BiDAlab/HuMIdb] Database availability (#1)


My name is ranjith, phd student and is looking for the Humidb database. I sent the e-mail request to ***@***.******@***.***>. can your please send the database as it would help me a lot
Regards
Ranjith

**Comment by ranjithven** [comment]
Please find the attached file


Regards
Ranjith

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BiDAlab** [comment]
sorry, we cannot download the file. Please, submitt the agreement directly to ***@***.***

Please note that you need to identify your institution or company.

Best,
Aythami.
________________________________
De: ranjithven ***@***.***>
Enviado: lunes, 17 de abril de 2023 12:26
Para: BiDAlab/HuMIdb ***@***.***>
Cc: Aythami Morales Moreno ***@***.***>; Comment ***@***.***>
Asunto: Re: [BiDAlab/HuMIdb] Database availability (#1)


Please find the attached file


Regards
Ranjith

Get Outlook for Android<https://aka.ms/AAb9ysg><https://urldefense.com/v3/__https://aka.ms/AAb9ysg*3E__;JQ!!D9dNQwwGXtA!TWuo72PXuCKerK5HJkdmV9S2R3AsFVMb6MIRQUh_mzPq8lpofNdKyAL3DSo2pyEFUZE-yfBxOTOVwd26bHuRz7wXXiZB$>
________________________________
